# Generated by Django 5.2.8 on 2025-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Camiseta Barcelona 2024 Home', max_length=200, verbose_name='Nombre de la camiseta')),
                ('equipo', models.CharField(max_length=100, verbose_name='Equipo')),
                ('temporada', models.CharField(help_text='Ej: 2023-2024', max_length=50, verbose_name='Temporada')),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3, verbose_name='Talla')),
                ('descripcion', models.TextField(help_text='Describe el estado, características, etc.', max_length=500, verbose_name='Descripción breve')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio ($)')),
                ('imagen', models.ImageField(help_text='Sube una foto clara de la camiseta', upload_to='camisetas/', verbose_name='Imagen de la camiseta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
            ],
            options={
                'verbose_name': 'Camiseta',
                'verbose_name_plural': 'Camisetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
